optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 3
  #pretrain_path: ./checkpoint/xxxx.pth

test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 256

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: gowalla

model:
  name: hccf # case-insensitive
  keep_rate: 1.0
  layer_num: 2
  reg_weight: 1.0e-7
  cl_weight: 1.0
  temperature: 1.0
  embedding_size: 32
  mult: 1.0e-3
  hyper_num: 16
  leaky: 0.5